apiVersion: v1
kind: Service
metadata:
  name: {{ include "soju.fullname" . }}
  labels:
    {{- include "soju.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  ports:
    - port: 6697
      targetPort: 6697
  selector:
    {{- include "soju.selectorLabels" . | nindent 4 }}
