apiVersion: v2
name: postgresql
description: A Helm chart for a shared PostgreSQL instance
version: 0.1.0
appVersion: "17"

dependencies:
  - name: ext-postgres-operator
    version: "3.0.0"
    repository: https://movetokube.github.io/postgres-operator/
