apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "miniflux.fullname" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/ttl: "300"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ include "miniflux.fullname" . }}-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "miniflux.fullname" . }}
                port:
                  number: 8080
