apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.admin.password | quote }}
