apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniflux.fullname" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "miniflux.selectorLabels" . | nindent 4 }}
