apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "soap-coffee.fullname" . }}
  labels:
    {{- include "soap-coffee.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "soap-coffee.fullname" . }}
                port:
                  number: 8901
