apiVersion: v1
kind: Service
metadata:
  name: {{ include "soap-coffee.fullname" . }}
  labels:
    {{- include "soap-coffee.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8901
      targetPort: 8901
  selector:
    {{- include "soap-coffee.selectorLabels" . | nindent 4 }}
